repos:
-   repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.9.0
    hooks:
    -   id: pre-commit-update
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-added-large-files # prevent accidentally adding large files to the repo
        args: ['--maxkb=500']  # Flag files over 500KB
    -   id: check-merge-conflict # prevent committing unresolved merge conflicts
    -   id: end-of-file-fixer # ensure files end with a newline
    -   id: trailing-whitespace # remove trailing whitespace
    -   id: check-toml # validates pyproject.toml syntax
    -   id: check-yaml # validates YAML syntax
        exclude: "docs/mkdocs.yml"
    -   id: no-commit-to-branch
        args: ["-b", dev]
        pass_filenames: false
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.0
    hooks:
    -   id: ruff-format
    -   id: ruff-check
