name: pre-commit
on:
  pull_request:
  push:
    branches: [dev]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      SKIP: no-commit-to-branch
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Run pre-commit on all files
        run: |
          uv sync --group dev
          uv run pre-commit run --all-files
